version: '3'

volumes:
  postgres_data: {}
  synapse_data: {}

services:
  synapse:
    image: docker.io/matrixdotorg/synapse:latest
    networks:
      - default
      - ldap
    # Since synapse does not retry to connect to the database, restart
    # upon failure
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/config/homeserver.yaml
    volumes:
      - synapse_data:/data
      - ./homeserver.yaml:/config/homeserver.yaml:ro
      - ./log_config.yaml:/config/log_config.yaml:ro
      - /srv/letsencrypt:/letsencrypt:ro
    depends_on:
      - db
    ports:
      - 8448:8448/tcp
      - 8008:8008/tcp
    external_links:
      - ldap

  nginx:
    image: nginx
    networks:
      - default
      - web
    links:
      - synapse
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - VIRTUAL_HOST=matrix.zfix.org,matrix.mrksr.de
      - CERT_NAME=shared

  db:
    image: docker.io/postgres:10-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  web:
    external:
      name: nginx_default
  ldap:
    external:
      name: ldap_default
